import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FoodContextProvider } from "@/utils/context";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { SavedMealProvider } from "@/utils/context";
import { UserProvider } from "@/utils/context";
import Protection from "@/components/LoginWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>

          <FoodContextProvider>
            <SavedMealProvider>
              <Header />
              <Protection>
                {children}
              </Protection>
              <Footer />
              <Toaster />
            </SavedMealProvider>
          </FoodContextProvider>

        </UserProvider>

      </body>
    </html>
  );
}
